name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Access Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          RABBITSTREAM_SOURCE_API: ${{ secrets.RABBITSTREAM_SOURCE_API }}
        run: |
          echo TMDB_API_KEY=$TMDB_API_KEY >> local.properties
          echo RABBITSTREAM_SOURCE_API=$RABBITSTREAM_SOURCE_API >> local.properties

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Unified
        run: |
          ./gradlew clean assembleRelease
          mkdir -p signed_apks
          cp app/build/outputs/apk/release/*.apk signed_apks/app-unified.apk
        
      - name: Sign Unified
        id: sign_unified
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: signed_apks
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Build Mobile
        run: |
          sed -i '/APP_LAYOUT/d' local.properties
          echo APP_LAYOUT=mobile >> local.properties
          ./gradlew clean assembleRelease
          mkdir -p signed_apks_mobile
          cp app/build/outputs/apk/release/*.apk signed_apks_mobile/app-mobile.apk
          
      - name: Sign Mobile
        id: sign_mobile
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: signed_apks_mobile
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Build TV
        run: |
          sed -i '/APP_LAYOUT/d' local.properties
          echo APP_LAYOUT=tv >> local.properties
          ./gradlew clean assembleRelease
          mkdir -p signed_apks_tv
          cp app/build/outputs/apk/release/*.apk signed_apks_tv/app-tv.apk
          
      - name: Sign TV
        id: sign_tv
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: signed_apks_tv
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.sign_unified.outputs.signedReleaseFile }}
            ${{ steps.sign_mobile.outputs.signedReleaseFile }}
            ${{ steps.sign_tv.outputs.signedReleaseFile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
